# Project information
site_name: An Attempt to Solution to Basic Graph Theory - Md. Saidur Rahman
site_url: https://asifajrof.github.io/graph-book-solve/
site_author: CSE 17
site_description: >-
    An Attempt to Solution to Basic Graph Theory - Md. Saidur Rahman
  
## Repository
repo_name: asifajrof/graph-book-solve
repo_url: https://github.com/asifajrof/graph-book-solve
edit_uri: ""

# Copyright

# Configuration
theme:
  name: material
  
  # Static files
  static_templates:
    - 404.html

  font:
    text: Bitter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
    - scheme: slate 
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - header.autohide
  logo: assets/graph_logo.svg
  favicon: assets/graph_logo.svg

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/asifajrof/graph-book-solve

# Page tree
nav:
  - Home: index.md
  - Disclaimer: disclaimer.md
  - Contents:
      - Chapter 1 - Graphs and Their Applications: chapters/chapter_01.md
      - Chapter 2 - Basic Graph Terminologies: chapters/chapter_02.md
      - Chapter 3 - Paths, Cycles and Connectivity: chapters/chapter_03.md
      - References: references.md
      # - License: license.md
      # - Changelog:
      # - Changelog/index.md
      # - Reference:
      # - Blog:

# Extensions
markdown_extensions:
  # - abbr
  # - admonition
  - attr_list
  # - def_list
  - footnotes
  # - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
